version: "3.8"
services:
  mongo:
    image: docker.io/library/mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongoadmin:secret@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
